In [29]:
from math import sqrt
from numpy import concatenate
from matplotlib import pyplot
from pandas import read_csv
from pandas import DataFrame
from pandas import concat
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
csv = pd.read_csv('/Users/shenghaoisyummy/Capstone/feature_extraction_data_dummis.csv', index_col=0, header=0)

In [30]:
dataset = csv
dataset = dataset.astype('float32')


In [31]:
dataset

-60.0    0.0  -780.0  0.0.1  0.0.2  0.0.3  0.0.4  0.0.5  0.0.6  0.0.7  \
2                                                                           
3   -60.0    0.0   -60.0    0.0 -840.0    0.0 -420.0    0.0 -420.0    0.0   
4   -60.0   60.0   -60.0    0.0 -120.0    0.0  -60.0    0.0  -60.0    0.0   
5  -120.0    0.0   -60.0   60.0 -120.0   60.0  -60.0   30.0  -60.0   30.0   
6   -60.0    0.0  -120.0    0.0 -180.0   60.0  -90.0   30.0  -90.0   30.0   
7   -60.0    0.0   -60.0    0.0 -180.0    0.0  -90.0    0.0  -90.0    0.0   
8   -60.0    0.0   -60.0    0.0 -120.0    0.0  -60.0    0.0  -60.0    0.0   
9   -60.0    0.0   -60.0    0.0 -120.0    0.0  -60.0    0.0  -60.0    0.0   
10  -60.0    0.0   -60.0    0.0 -120.0    0.0  -60.0    0.0  -60.0    0.0   
11 -120.0    0.0   -60.0    0.0 -120.0    0.0  -60.0    0.0  -60.0    0.0   
12 -120.0    0.0  -120.0    0.0 -180.0    0.0  -90.0    0.0  -90.0    0.0   
13  -60.0  -60.0  -120.0    0.0 -240.0    0.0 -120.0    0.0 -120.0    0.0   
14 -120.0    0.0   -60.0  -60.0 -180.0  -60.0  -90.0  -30.0  -90.0  -30.0   
15 -120.0    0.0  -120.0    0.0 -180.0  -60.0  -90.0  -30.0  -90.0  -30.0   
16    0.0 -360.0  -120.0    0.0 -240.0    0.0 -120.0    0.0 -120.0    0.0   
17    0.0    0.0     0.0 -360.0 -120.0 -360.0  -60.0 -180.0  -60.0 -180.0   
18    0.0    0.0     0.0    0.0    0.0 -360.0    0.0 -180.0    0.0 -180.0   
19    0.0  -60.0     0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
20    0.0  -60.0     0.0  -60.0    0.0  -60.0    0.0  -30.0    0.0  -30.0   
21 -120.0 -120.0     0.0  -60.0    0.0 -120.0    0.0  -60.0    0.0  -60.0   
22 -120.0 -480.0  -120.0 -120.0 -120.0 -180.0  -60.0  -90.0  -60.0  -90.0   
23  -60.0 -120.0  -120.0 -480.0 -240.0 -600.0 -120.0 -300.0 -120.0 -300.0   
24  -60.0 -120.0   -60.0 -120.0 -180.0 -600.0  -90.0 -300.0  -90.0 -300.0   
25  -60.0  -60.0   -60.0 -120.0 -120.0 -240.0  -60.0 -120.0  -60.0 -120.0   
26  -60.0  -60.0   -60.0  -60.0 -120.0 -180.0  -60.0  -90.0  -60.0  -90.0   
27 -180.0 -180.0   -60.0  -60.0 -120.0 -120.0  -60.0  -60.0  -60.0  -60.0   
28 -120.0 -120.0  -180.0 -180.0 -240.0 -240.0 -120.0 -120.0 -120.0 -120.0   
29    0.0  -60.0  -120.0 -120.0 -300.0 -300.0 -150.0 -150.0 -150.0 -150.0   
30    0.0  -60.0     0.0  -60.0 -120.0 -180.0  -60.0  -90.0  -60.0  -90.0   
31  -60.0 -180.0     0.0  -60.0    0.0 -120.0    0.0  -60.0    0.0  -60.0   
32  -60.0  -60.0   -60.0 -180.0  -60.0 -240.0  -30.0 -120.0  -30.0 -120.0   
..    ...    ...     ...    ...    ...    ...    ...    ...    ...    ...   
8    60.0  180.0    60.0  120.0   60.0  240.0   30.0  120.0   30.0  120.0   
9    60.0  120.0    60.0  180.0  120.0  300.0   60.0  150.0   60.0  150.0   
10  120.0  120.0    60.0  120.0  120.0  300.0   60.0  150.0   60.0  150.0   
11   60.0  120.0   120.0  120.0  180.0  240.0   90.0  120.0   90.0  120.0   
12   60.0  180.0    60.0  120.0  180.0  240.0   90.0  120.0   90.0  120.0   
13  120.0  180.0    60.0  180.0  120.0  300.0   60.0  150.0   60.0  150.0   
14  120.0  240.0   120.0  180.0  180.0  360.0   90.0  180.0   90.0  180.0   
15  120.0  240.0   120.0  240.0  240.0  420.0  120.0  210.0  120.0  210.0   
16  180.0  120.0   120.0  240.0  240.0  480.0  120.0  240.0  120.0  240.0   
17  180.0  180.0   180.0  120.0  300.0  360.0  150.0  180.0  150.0  180.0   
18  240.0  240.0   180.0  180.0  360.0  300.0  180.0  150.0  180.0  150.0   
19  240.0  180.0   240.0  240.0  420.0  420.0  210.0  210.0  210.0  210.0   
20  240.0  180.0   240.0  180.0  480.0  420.0  240.0  210.0  240.0  210.0   
21  240.0  240.0   240.0  180.0  480.0  360.0  240.0  180.0  240.0  180.0   
22  240.0  180.0   240.0  240.0  480.0  420.0  240.0  210.0  240.0  210.0   
23  240.0  180.0   240.0  180.0  480.0  420.0  240.0  210.0  240.0  210.0   
24  240.0  180.0   240.0  180.0  480.0  360.0  240.0  180.0  240.0  180.0   
25  240.0  240.0   240.0  180.0  480.0  360.0  240.0  180.0  240.0  180.0   
26  240.0  240.0   240.0  240.0  480.0  420.0  240.0  210.0  240.0  210.0   


In [32]:
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)

In [33]:
dataset

array([[0.84328358, 0.75793651, 0.84328358, ..., 0.        , 0.        ,
        0.        ],
       [0.84328358, 0.76190476, 0.84328358, ..., 1.        , 0.        ,
        0.        ],
       [0.84079602, 0.75793651, 0.84328358, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.84825871, 0.76190476, 0.85572139, ..., 1.        , 0.        ,
        0.        ],
       [0.84825871, 0.75793651, 0.84825871, ..., 0.        , 0.        ,
        0.        ],
       [0.84577114, 0.70238095, 0.84825871, ..., 0.        , 0.        ,
        1.        ]])

In [34]:
train_size = int(len(dataset) * 0.80)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size, :], dataset[train_size:len(dataset), :]
print(len(train), len(test))

14361 3591


In [35]:
def create_dataset(dataset, look_back=1):
  dataX, dataY = [], []
  for i in range(len(dataset)-look_back-1):
    a = dataset[i:(i+look_back), 0]
    dataX.append(a)
    dataY.append(dataset[i + look_back, 0])
  return np.array(dataX), np.array(dataY)

In [36]:
look_back = 10
trainX, trainY = create_dataset(train, look_back=look_back)
testX, testY = create_dataset(test, look_back=look_back)

In [37]:
trainX

array([[0.84328358, 0.84328358, 0.84079602, ..., 0.84328358, 0.84079602,
        0.84079602],
       [0.84328358, 0.84079602, 0.84328358, ..., 0.84079602, 0.84079602,
        0.84328358],
       [0.84079602, 0.84328358, 0.84328358, ..., 0.84079602, 0.84328358,
        0.84079602],
       ...,
       [0.84577114, 0.84577114, 0.84825871, ..., 0.84825871, 0.84825871,
        0.84825871],
       [0.84577114, 0.84825871, 0.84825871, ..., 0.84825871, 0.84825871,
        0.84825871],
       [0.84825871, 0.84825871, 0.84825871, ..., 0.84825871, 0.84825871,
        0.84825871]])

In [38]:
trainY

array([0.84328358, 0.84079602, 0.84079602, ..., 0.84825871, 0.84825871,
       0.84577114])

In [39]:
trainX = np.reshape(trainX, (trainX.shape[0], 1, trainX.shape[1]))
testX = np.reshape(testX, (testX.shape[0], 1, testX.shape[1]))

In [43]:
model = Sequential()
model.add(LSTM(4, input_shape=(1, look_back)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, trainY, epochs=100, batch_size=256, verbose=2)

Epoch 1/100
 - 3s - loss: 0.6336
Epoch 2/100
 - 0s - loss: 0.2503
Epoch 3/100
 - 0s - loss: 0.0642
Epoch 4/100
 - 0s - loss: 0.0084
Epoch 5/100
 - 0s - loss: 9.2886e-04
Epoch 6/100
 - 0s - loss: 5.6585e-04
Epoch 7/100
 - 0s - loss: 5.5931e-04
Epoch 8/100
 - 0s - loss: 5.5913e-04
Epoch 9/100
 - 0s - loss: 5.5914e-04
Epoch 10/100
 - 0s - loss: 5.5897e-04
Epoch 11/100
 - 0s - loss: 5.5897e-04
Epoch 12/100
 - 0s - loss: 5.5883e-04
Epoch 13/100
 - 0s - loss: 5.5875e-04
Epoch 14/100
 - 0s - loss: 5.5883e-04
Epoch 15/100
 - 0s - loss: 5.5869e-04
Epoch 16/100
 - 0s - loss: 5.5862e-04
Epoch 17/100
 - 0s - loss: 5.5868e-04
Epoch 18/100
 - 0s - loss: 5.5838e-04
Epoch 19/100
 - 0s - loss: 5.5844e-04
Epoch 20/100
 - 0s - loss: 5.5824e-04
Epoch 21/100
 - 0s - loss: 5.5836e-04
Epoch 22/100
 - 0s - loss: 5.5805e-04
Epoch 23/100
 - 0s - loss: 5.5800e-04
Epoch 24/100
 - 0s - loss: 5.5800e-04
Epoch 25/100
 - 0s - loss: 5.5777e-04
Epoch 26/100
 - 0s - loss: 5.5777e-04
Epoch 27/100
 - 0s - loss: 5.5764e-04

In [44]:
trainPredict = model.predict(trainX)
testPredict = model.predict(testX)

In [45]:
trainPredicttrainPre  = scaler.inverse_transform(trainPredict)
trainY = scaler.inverse_transform([trainY])
testPredict = scaler.inverse_transform(testPredict)
testY = scaler.inverse_transform([testY])

ValueError: non-broadcastable output operand with shape (14350,1) doesn't match the broadcast shape (14350,220)